### ISSUE TITLE
Attach inventory to contract

### ISSUE THREAD

**Issue by CBranagan** [Fawlty22/skiHaus#10]
Attach inventory to Contract Model

**Comment by CBranagan** [comment]
Be able to attach inventory to the equipment array in the contract model if it is "available". Set inventory to "in-use" so it can not be attached to another contract

**Comment by Fawlty22** [comment]
I discussed this with my tutor, and will be addressing this shortly.  The plan is to add an "available" property to each piece of equipment and set its value to a boolean defaulting to true. Then upon adding a piece of equipment to the contract, the resolver will run a Ski.findOneandUpdate, or board or boot, and toggle the boolean.  Thus, whenever we query for skis, we just make sure to query for Skis.available

**Comment by Fawlty22** [comment]
Closing this, as I think I've completed it.
