### ISSUE TITLE
Check in Equipment and close contract

### ISSUE THREAD

**Issue by CBranagan** [Fawlty22/skiHaus#12]
Remove contract from customer model and set contract to "complete". Set inventory from the equipment array to "available". be able to update the condition of the equipment?

**Comment by Fawlty22** [comment]
Just want to jot down thoughts while ive got em.
resolver would look something like:

Contract.findOneandUpdate to closed
if (skis){
ski.FindOneandUpdate to toggle the available boolean
}
repeat for boards and boots

**Comment by Fawlty22** [comment]
Closing this as I believe I've completed it. Alan will be handling the edit resolvers/typedefs for specific equipment.
